landingpage/urls.py
from django.urls import path
from .views import home

app_name = 'landingpage'

urlpatterns = [
	path('', home, name='home'),
	]

story_6/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('landingpage.urls')),
]

landingpage/models.py
from django.db import models
# Create your models here.
class Status (models.Model):
    description = models.CharField(max_length=300)
    date = models.DateField()
    

landingpage/forms.py
from django import forms
import datetime

class Message_Form(forms.Form):
    description = forms.CharField(label='activity', required=True, max_length=300, widget=forms.TextInput(attrs = {"class": "form-control"}))

landingpage/views.py
from django.shortcuts import render
from datetime import datetime, date
from .forms import *
from .models import *

# Create your views here.

def home(request):
    form = Message_Form()
    status = Status.objects.all()
    response = {'message_form': form, 'mystatus' : status}
    if request.method == 'POST':
        description = request.POST['description']
        status = Status(description=description,date=datetime.datetime.now())
        status.save()
    return render(request, 'home.html', response)

landingpage/templates/home.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
  <link rel= "stylesheet" href= "{% static 'bootstrap.min.css' %}">
  <link rel= "stylesheet" href= "{% static 'home.css' %}">
   
  
    <title>{{ Hello }}</title>
</head>
<body>
<h1>
Halo apa kabar?
</h1>

<div class="container-fluid">
  <div class="row justify-content-center">
      <section name="form">
      <br>
      <br>
      <br>
      <form id="form" method="POST" action = "{% url 'landingpage:home' %}">
      {% csrf_token %}
      {{ message_form }} 
      <br>
      <button type="submit" class="btn btn-primary"> POST </button>
      </form>
      </section>
      <br>
      <br>
      <br>
      <br>
      </div>

    <div class="row">
    
    <table class="table">
    <thead>
      <tr>
        <th>Description</th>
        <th>Date</th>
      </tr>
    </thead>
    <tbody>
    {% for h in mystatus %}
      <tr>
        <td> {{ h.description }} </td>
        <td> {{ h.date }} </td>
      </tr>
      {% endfor %}
    </tbody>
  </table>
</div>

</body>